- name: "[INSTALL] - Install reverse proxy"
  ansible.builtin.package:
    name: "{{ nextcloud_reverseproxy }}"
    state: present
  notify: Stop reverseproxy

- name: "[INSTALL] - Install naxsi module on nginx"
  ansible.builtin.apt:
    deb: "https://github.com/wargio/naxsi/releases/download/1.6/{{ server_os }}-{{ server_release }}-libnginx-mod-http-naxsi_1.6_amd64.deb"

- name: "[REVERSEPROXY NGINX] - Create link on naxsi_core.rules"
  ansible.builtin.file:
    src: /usr/share/naxsi/naxsi_core.rules
    dest: /etc/nginx/conf.d/naxsi_core.rules.conf
    state: link

- name: "[REVERSEPROXY NGINX] - Generate naxsi configuration for nginx"
  ansible.builtin.template:
    dest: /etc/nginx/naxsi.rules
    src: "templates/reverseproxy_naxsi_nc.j2"
    mode: 0640
  notify: Reload reverseproxy

- name: "[REVERSEPROXY NGINX] - Generate Nextcloud configuration for nginx"
  ansible.builtin.template:
    dest: /etc/nginx/sites-available/reverseproxy_{{ nextcloud_instance_name }}.cnf
    src: "{{ nextcloud_reverseproxy_template }}"
    mode: 0640
  notify: Reload reverseproxy

- name: "[REVERSEPROXY NGINX] - Enable Nextcloud in nginx conf"
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/reverseproxy_{{ nextcloud_instance_name }}
    src: /etc/nginx/sites-available/reverseproxy_{{ nextcloud_instance_name }}.cnf
    state: link
  notify: Reload reverseproxy
