- name: "[INSTALL] - Install reverse proxy"
  ansible.builtin.package:
    name: "{{ nextcloud_reverseproxy }}"
    state: present
  notify: Stop reverseproxy

- name: "[INSTALL] - Install naxsi module on nginx"
  ansible.builtin.apt:
    deb: "https://github.com/nbs-system/naxsi/releases/download/1.3/{{ server_os }}-{{ server_release }}-libnginx-mod-http-naxsi_1.3_amd64.deb"

- name: "[REVERSEPROXY NGINX] - Add naxsi to nginx.conf"
  ansible.builtin.lineinfile:
    path: /etc/{{ nextcloud_reverseproxy }}/{{ nextcloud_reverseproxy }}.conf
    insertafter: '# Basic Settings\n\t##\n'
    line: 'include /usr/share/naxsi/naxsi_core.rules;'
  notify: Reload reverseproxy

    - name: "[REVERSEPROXY NGINX] - Generate naxsi configuration for nginx"
  ansible.builtin.template:
    dest: /etc/nginx/naxsi.rules
    src: "templates/reverseproxy_naxsi_nc.j2"
    mode: 0640
  notify: Reload reverseproxy

- name: "[REVERSEPROXY NGINX] - Generate Nextcloud configuration for nginx"
  ansible.builtin.template:
    dest: /etc/nginx/sites-available/reverseproxy_{{ nextcloud_instance_name }}.cnf
    src: "{{ nextcloud_reverseproxy_template }}"
    mode: 0640
  notify: Reload reverseproxy

- name: "[REVERSEPROXY NGINX] - Enable Nextcloud in nginx conf"
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/reverseproxy_{{ nextcloud_instance_name }}
    src: /etc/nginx/sites-available/reverseproxy_{{ nextcloud_instance_name }}.cnf
    state: link
  notify: Reload reverseproxy
